apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizontalpodautoscalers.autoscaling
spec:
  group: autoscaling
  versions:
    - name: v2beta2
      served: true
      storage: true
  names:
    kind: HorizontalPodAutoscaler
    plural: horizontalpodautoscalers
    singular: horizontalpodautoscaler
  scope: Namespaced
