apiVersion: v1
kind: Service
metadata:
  name: aoba-service
spec:
  selector:
    app: aoba-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
